liquibase/liquibase-databricks

pom.xml
It's required for the maven central and was forgotten
=> Added name attribute to pom.xml

pom.xml
... to improve security
Fix for Error: `Error:  Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project liquibase-databricks: Unable to commit files`
https://github.com/liquibase/liquibase-databricks/actions/runs/6354762339/job/17317658988#step:5:277
=> change git connection URL to use HTTPS instead of HTTP.. 

pom.xml, src/main/java/liquibase/ext/databricks/datatype/BooleanDatatypeDatabricks.java, src/main/java/liquibase/ext/databricks/datatype/DoubleDatatypeDatabricks.java, src/main/java/liquibase/ext/databricks/datatype/FloatDatatypeDatabricks.java, src/main/java/liquibase/ext/databricks/datatype/IntegerDatatypeDatabricks.java, src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
Add snapshot reflection support for the following databricks data types: -- Float
-- Double
-- Bool
=> Add reflection support for new data types

src/main/java/liquibase/ext/databricks/database/DatabricksDatabase.java, src/main/java/liquibase/ext/databricks/datatype/StringDatatypeDatabricks.java
=> [DAT-18108] added clob as string alias

.github/workflows/lth.yml, src/test/terraform/auth.tf, src/test/terraform/dbsql_endpoint.tf, src/test/terraform/schema.auto.tfvars, src/test/terraform/schema.tf
Force recreation by changing the endpoint name dynamically. It will trigger Terraform to destroy the existing resource and create a new one. This will ensure that a new SQL endpoint is created each time you apply the Terraform configuration, as the name will always be unique.
🔧 (auth.tf): Update type assignment formatting for DBX_TOKEN variablefor consistency
✨ (dbsql_endpoint.tf): Add random suffix to endpoint name for uniqueness
♻️ (schema.auto.tfvars): Align TF_VAR_TEST_CATALOG and TF_VAR_TEST_SCHEMA assignments for consistency
♻️ (schema.tf): Refactor type and default assignments for TF_VAR_TEST_SCHEMA, TF_VAR_TEST_CATALOG, and schema_force_destroy variables for consistency
=> [DAT-18567] DevOps :: liquibase-databricks terraform fails to recreate IT tests schema

.github/workflows/lth.yml, src/test/java/liquibase/ext/databricks/AdvancedExtensionHarnessTestSuite.java, src/test/resources/liquibase/harness/snapshot/changelogs/databricks/addColumn.xml, src/test/resources/liquibase/harness/snapshot/changelogs/databricks/addPrimaryKey.xml, src/test/resources/liquibase/harness/snapshot/changelogs/databricks/addUniqueConstraint.xml, src/test/resources/liquibase/harness/snapshot/changelogs/databricks/createTable.xml, src/test/resources/liquibase/harness/snapshot/changelogs/databricks/createView.xml, src/test/resources/liquibase/harness/snapshot/changelogs/databricks/snapshotCatalogAndSchema.xml, src/test/resources/liquibase/harness/snapshot/expectedSnapshot/databricks/addColumn.json, src/test/resources/liquibase/harness/snapshot/expectedSnapshot/databricks/addUniqueConstraint.json, src/test/resources/liquibase/harness/snapshot/expectedSnapshot/databricks/createTable.json, src/test/resources/liquibase/harness/snapshot/expectedSnapshot/databricks/createView.json, src/test/resources/liquibase/harness/snapshot/expectedSql/addUniqueConstraint.sql, src/test/resources/liquibase/harness/snapshot/expectedSql/createIndex.sql, src/test/resources/liquibase/harness/snapshot/expectedSql/createSequense.sql
Generate changelog test disabled for now as it has issue on test-harenss side.
Worked on local run with JDBC connection and used main.mykhailo Databricks schema.
=> DAT-18667: Updated snapshot test suite test files. 

src/main/java/liquibase/ext/databricks/parser/NamespaceDetailsDatabricks.java, src/main/resources/META-INF/services/liquibase.parser.NamespaceDetails
The commit from this PR was cherry picked to https://github.com/liquibase/liquibase-databricks/pull/191 . Commit https://github.com/liquibase/liquibase-databricks/pull/191/commits/7feee50a690ee8d030d699838e75a94fad8e0b28 was created on top of that to prepend  "databricks:"  to the tags when generating changelog.
=> feat: Generated Snapshots should reference Databricks XSD

.github/workflows/lth.yml
fix: `.github/workflows/lth.yml` : specify `-Dliquibase.version` in both commands to ensure that we have consistent behaviour and to use the latest liquibase-core snapshot during workflow runs.
=> DAT-18668: use -Dliquibase.version=master-SNAPSHOT

src/main/java/liquibase/ext/databricks/change/AbstractAlterPropertiesChangeDatabricks.java, src/main/java/liquibase/ext/databricks/diff/output/changelog/ChangedTableChangeGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/diff/output/changelog/ChangedTblPropertiesUtil.java, src/main/java/liquibase/ext/databricks/diff/output/changelog/ChangedViewChangeGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/snapshot/jvm/TableSnapshotGeneratorDatabricks.java, src/main/resources/META-INF/services/liquibase.diff.output.changelog.ChangeGenerator, src/test/java/liquibase/ext/databricks/diff/output/changelog/ChangedTblPropertiesUtilTest.java
- Added `ChangedTableChangeGeneratorDatabricks` class to handle Databricks-specific table property changes.
- Implemented logic to compare and generate changes for table properties.
- Updated `META-INF/services/liquibase.diff.output.changelog.ChangeGenerator` to include the new change generator.
=> feat(DAT-18853): Add custom diff change generator for Databricks

src/main/java/liquibase/ext/databricks/diff/output/changelog/ChangedTblPropertiesUtil.java, src/main/java/liquibase/ext/databricks/diff/output/changelog/MissingTableChangeGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/diff/output/changelog/MissingViewChangeGeneratorDatabricks.java
fix: delta properties for tables/views should not be present in the extendedTableProperties changeSet for generated changelogs and diff-changelog when referenceDB is empty.
=> fix(DAT-18966): hide delta properties for tables/views

src/main/java/liquibase/ext/databricks/database/DatabricksDatabase.java
Tested all 3 cases with non existing catalog and/or non existing schema.
=> DAT-18491: Added verification of user specified schema and catalog inconnection uri

src/main/java/liquibase/ext/databricks/diff/output/changelog/MissingColumnChangeGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/snapshot/jvm/ColumnSnapshotGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/sqlgenerator/AddDefaultValueGeneratorDatabricks.java, src/main/resources/META-INF/services/liquibase.diff.output.changelog.ChangeGenerator, src/test/java/liquibase/ext/databricks/snapshot/jvm/ColumnSnapshotGeneratorDatabricksTest.java
Databricks fails to add column to an existing delta table if there are defined default value or not null constraint. This was found by Pavlo and during my e2e test.
In this ticket for missing columns it was performed splitting of `addColumnChange` to three changes `addColumnChange`, `addDefaultValie`, `addNotNullConstraintChange` if they are required.
Testing was performed with tables having different hanged default values, absent and unexpected columns.
As a test case i used run `diff-changelog`, run `update` with previously generated changelog file, run diff to make sure there are not changed entities left.
=> DAT-19050: adding missing column is splitted on addColumn and add{Constraint} changetypes

.github/workflows/attach-artifact-release.yml
This pull request includes a small change to the `.github/workflows/attach-artifact-release.yml` file. The change adds a `workflow_dispatch` trigger to the workflow configuration.
* [`.github/workflows/attach-artifact-release.yml`](diffhunk://#diff-4e6cdd9dccb26ce28aa3716a4046b99dd39c69e9319bf6b4e2922e6309c13b4aR7): Added `workflow_dispatch` trigger to allow manual triggering of the workflow.
=> ✨ : Update attach-artifact-release.yml

src/main/java/liquibase/ext/databricks/diff/output/changelog/MissingColumnChangeGeneratorDatabricks.java
Super class returns null for views, need to count that in Databricks class
MissingColumnChangeGenerator.fixMissing()
```        
if (column.getRelation() instanceof View) {
return null;
}
```
=> [no_jira] fixed processing null Changes in MissingColumnChangeGeneratorDatabricks

pom.xml, src/test/java/liquibase/ext/databricks/AdvancedExtensionHarnessTestSuite.java, src/test/resources/liquibase/harness/generateChangelog/expectedChangeLog/databricks/createTable.sql, src/test/resources/liquibase/harness/generateChangelog/expectedSql/databricks/createTable.sql
The system was encountering a `/null` path issue when attempting to locate the createTable.sql file, affecting the test reliability.
- Modified the cleanup mechanism in `GenerateChangelogTest` to correctly target and remove generated files in the `src/test/resources/generated/` directory
- Implemented a pre-test cleanup routine to ensure a clean state before test execution
- Fixed the path resolution logic for SQL file lookup
The test execution now shows successful cleanup operations:
=> DAT-18731 - Resolving the /null problem when not finding the createTable.sql

.github/workflows/lth.yml, README.md
This pull request includes changes to update the GitHub Actions workflow to include `ubuntu-22.04`. 
Seems like there is an issue with using `ubuntu-latest` ie `Ubuntu 24.10` for databricks. 
Workflow updates:
* [`.github/workflows/lth.yml`](diffhunk://#diff-a8d9f8fb2a632e7abc6b1fce50c961566e33a18fefafa230c2ed93f4924df003L17-R17): Updated the `runs-on` key from `ubuntu-latest` to `ubuntu-22.04` to ensure compatibility with the latest Ubuntu version.
=> use ubuntu-22.04 to run databricks

.github/workflows/lth.yml
This pull request includes significant changes to the GitHub Actions workflow configuration in the `.github/workflows/lth.yml` file. The changes primarily involve restructuring the jobs for better organization and dependency management.
Key changes include:
* **Job Renaming and Reorganization:**
* Renamed the `liquibase-test-harness` job to `start-test-harness-infra` and updated its name to "Start Liquibase Test Harness infra."
* Moved the `liquibase-test-harness` job to run after `start-test-harness-infra` and updated its configuration.
* **Environment Variables and Permissions:**
* Removed the environment variables `WORKSPACE_ID`, `LIQUIBOT_TOKEN`, and `GITHUB_TOKEN` from the `start-test-harness-infra` job.
* Added the removed environment variables and permissions back to the newly …
=> DAT-19348 DevOps :: refactor databricks test-harness workflow to run terraform once

src/main/java/liquibase/ext/databricks/snapshot/jvm/SchemaSnapshotGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/snapshot/jvm/TableSnapshotGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/snapshot/jvm/ViewSnapshotGeneratorDatabricks.java
liquibase/liquibase#5775 was merged and fixed a bug where some snapshot generators were not being called.
But it also highlighted one issue at least in one OSS extension: if then extension replaces a core generator but is not implementing the replaces method, both generators may be invoked now.
This PR implements the missing replaces method.
=> fix: add missing replaces method for Snapshot Generator

.github/workflows/lth.yml
This pull request includes a small change to the `.github/workflows/lth.yml` file. The change removes the `pull_request` trigger from the workflow configuration for the Liquibase Test Harness.
The QA Team want to have possibility to start the tests on workflow_dispacth and to run automatic builds only on merge to master for databricks.
=> DAT-20404: update trigger of the job schedule

src/main/java/liquibase/ext/databricks/snapshot/jvm/ColumnSnapshotGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/snapshot/jvm/TableSnapshotGeneratorDatabricks.java, src/main/java/liquibase/ext/databricks/snapshot/jvm/ViewSnapshotGeneratorDatabricks.java
Added handling of `addTo()` cases using parent's priority logic.
Example of priority handling:
https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/snapshot/jvm/JdbcSnapshotGenerator.java#L40-L55
```
if (database instanceof AbstractJdbcDatabase) {
if ((defaultFor != null) && defaultFor.isAssignableFrom(objectType)) {
return PRIORITY_DEFAULT;
}
if (addsTo() != null) {
for (Class<? extends DatabaseObject> type : addsTo()) {
if (type.isAssignableFrom(objectType)) {
return PRIORITY_ADDITIONAL;
}
}
}
}
return PRIORITY_NONE;
```
=> INT-1381: Fix of Table, View and Column Snapshot generation flow.
